# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
include:
  project: "souvap/tooling/gitlab-config"
  ref: "main"
  file:
    - "ci/common/lint.yml"
    - "ci/container/container-build.yml"

stages:
  - ".pre"
  - "lint"
  - "build"
  - ".post"

container-build:
  variables:
    BUILD_DESTINATION: "${CI_REGISTRY_IMAGE}:0.5.10"

...
